# Tomcat
#server:
#    tomcat:
#        uri-encoding: UTF-8
#    port: 8082
#    servlet:
#      context-path: /mail

spring:
    # JavaMailSender 邮件发送的配置
    mail:
        host: smtp.163.com  # smtp.exmail.qq.com
        port: 465
        # todo
        username: xxxx@163.com
        password: yourPassword
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                      enable: true
                      required: true
#                    socketFactory:
#                      class: javax.net.ssl.SSLSocketFactory
#                      fallback: false
                    ssl:
                      enable: true
